In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Tipos de suelos-d1403_reverso.csv")
df.head()

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Relieve,Cobertura de la tierra,% de arcillas,...,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos,Carbonatos,Sulfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Abrupto,Selva caducifolia,6,...,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4,0.0,0.0
1,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Abrupto,Selva caducifolia,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Abrupto,Selva subcaducifolia,12,...,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0,0.0,0.0
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Abrupto,Selva subcaducifolia,14,...,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1,0.0,0.0
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Abrupto,Selva subcaducifolia,12,...,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5,0.0,0.0

In [2]:
df.shape

(85, 23)

In [3]:
df.columns

Index(['Identificador del sitio', 'Fecha', 'Clave WRB 2014', 'Grupo suelo',
       'Altitud', 'Precipitacion media anual', 'Temperatura media anual',
       'Relieve', 'Cobertura de la tierra', '% de arcillas', '% de limo',
       '% de arena', 'PH', 'Carbon organico', 'saturacion de bases',
       'Saturacion de sodio', 'Potasio', 'Calcio', 'Sodio', 'Magnesio',
       'Fosfatos', 'Carbonatos', 'Sulfatos'],
      dtype='object')

In [4]:
#Eliminar columnas
columnas_eliminar = [
    "Relieve",
    "% de arcillas",
    "% de limo",
    "% de arena"
]

df_limpio = df.drop(columns=columnas_eliminar)
df_limpio.head()

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos,Carbonatos,Sulfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,5.8,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4,0.0,0.0
1,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.0,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0,0.0,0.0
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.1,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1,0.0,0.0
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5,0.0,0.0

In [5]:
df_limpio.isnull().sum()

Identificador del sitio      0
Fecha                        0
Clave WRB 2014               0
Grupo suelo                  0
Altitud                      0
Precipitacion media anual    0
Temperatura media anual      0
Cobertura de la tierra       0
PH                           8
Carbon organico              8
saturacion de bases          8
Saturacion de sodio          8
Potasio                      8
Calcio                       8
Sodio                        8
Magnesio                     8
Fosfatos                     8
Carbonatos                   8
Sulfatos                     8
dtype: int64

In [6]:
df_limpio["faltantes_por_fila"] = df_limpio.isnull().sum(axis=1)
df_limpio[["faltantes_por_fila"]].head(20)

    faltantes_por_fila
0                    0
1                   11
2                    0
3                    0
4                    0
5                    0
6                    0
7                    0
8                    0
9                    0
10                   0
11                   0
12                   0
13                   0
14                   0
15                  11
16                   0
17                   0
18                  11
19                   0

In [7]:
df_limpio[df_limpio["faltantes_por_fila"] > 5]

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos,Carbonatos,Sulfatos,faltantes_por_fila
1,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
15,D1403-124,08/10/1986,RGlep-eu/1P,Regosol,100,800,26,Selva caducifolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
18,D1403-133,12/10/1986,RGlep-sk-eu/1P,Regosol,100,1000,26,Selva subcaducifolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
22,D1403-134,10/10/1986,"RGlen-ok-eu(arp,lon)/1P",Regosol,150,1000,26,Selva caducifolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
34,D1403-202,20/10/2004,"UMlen-al(ap,cr,loa)/2",Umbrisol,1120,3000,20,Bosque mesófilo de montaña,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
38,D1403-203,21/10/2004,"RGlen-je(arn,lop)/1",Regosol,110,1000,26,Selva caducifolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
71,D1403-301,09/09/2013,RGlen-eu(ara)/1,Regosol,343,1000,26,Pastizal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
79,D1403-303,11/09/2013,"LVlen(df,lo)/2",Luvisol,176,1000,26,Selva caducifolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11

In [8]:
df_limpio = df_limpio[df_limpio["faltantes_por_fila"] <= 5]
df_limpio = df_limpio.drop(columns=["faltantes_por_fila"])

In [9]:
df_limpio

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos,Carbonatos,Sulfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,5.8,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4,0.0,0.0
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.0,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0,0.0,0.0
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.1,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1,0.0,0.0
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5,0.0,0.0
5,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.3,76.6,0.0,0.1,9.4,0.0,1.6,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,6.8,0.8,49.0,1.4,0.7,9.3,0.4,4.1,0.5,0.0,0.0
81,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.2,0.9,22.6,1.1,0.2,3.5,0.3,2.1,0.1,0.0,0.0
82,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.0,0.5,18.7,1.1,0.1,2.9,0.4,2.5,0.0,0.0,0.0
83,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.1,0.3,24.7,1.6,0.1,2.6,0.4,2.8,0.0,0.0,0.0
84,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.6,0.5,23.5,1.0,0.1,2.5,0.3,3.4,0.0,0.0,0.0

In [10]:
# Reiniciar índice
df_limpio = df_limpio.reset_index(drop=True)

# Ver resultado
df_limpio.head()

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos,Carbonatos,Sulfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,5.8,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4,0.0,0.0
1,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.0,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0,0.0,0.0
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.1,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1,0.0,0.0
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5,0.0,0.0
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.3,76.6,0.0,0.1,9.4,0.0,1.6,0.0,0.0,0.0

In [11]:
df_limpio["Carbonatos"].value_counts(dropna=False)

Carbonatos
0.0     76
14.8     1
Name: count, dtype: int64

In [12]:
df_limpio["Sulfatos"].value_counts(dropna=False)

Sulfatos
0.0    77
Name: count, dtype: int64

In [13]:
df_limpio = df_limpio.drop(columns=["Carbonatos", "Sulfatos"])
df_limpio.columns

Index(['Identificador del sitio', 'Fecha', 'Clave WRB 2014', 'Grupo suelo',
       'Altitud', 'Precipitacion media anual', 'Temperatura media anual',
       'Cobertura de la tierra', 'PH', 'Carbon organico',
       'saturacion de bases', 'Saturacion de sodio', 'Potasio', 'Calcio',
       'Sodio', 'Magnesio', 'Fosfatos'],
      dtype='object')

In [14]:
df_limpio.head()

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,5.8,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4
1,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.0,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.1,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.3,76.6,0.0,0.1,9.4,0.0,1.6,0.0

In [15]:
df_limpio["PH"].value_counts(dropna=False)

PH
6.1    7
6.2    6
7.5    5
5.9    5
6.0    4
5.8    4
7.1    4
5.7    3
6.8    3
7.2    3
6.6    3
5.5    2
5.6    2
6.5    2
7.3    2
0.0    2
7.6    2
6.3    2
6.7    2
7.0    2
7.7    1
7.9    1
5.4    1
8.3    1
7.4    1
4.6    1
5.2    1
5.3    1
5.0    1
6.9    1
6.4    1
4.9    1
Name: count, dtype: int64

In [16]:
df_limpio[df_limpio["PH"] == 0]

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos
11,D1403-120,11/10/1986,"LVro(cep,ct,hu,lon)/3P",Luvisol,250,1200,26,Selva caducifolia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,D1403-133,12/10/1986,RGlep-sk-eu/1P,Regosol,100,1000,26,Selva subcaducifolia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
df_limpio = df_limpio[df_limpio["PH"] != 0]
df_limpio.head(12)

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,5.8,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4
1,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.0,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.1,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.3,76.6,0.0,0.1,9.4,0.0,1.6,0.0
5,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.6,0.2,39.9,0.0,0.0,5.4,0.0,2.1,0.0
6,D1403-120,11/10/1986,"LVro(cep,ct,hu,lon)/3P",Luvisol,250,1200,26,Selva caducifolia,6.0,2.0,53.0,0.0,0.3,9.4,0.0,2.5,2.7
7,D1403-120,11/10/1986,"LVro(cep,ct,hu,lon)/3P",Luvisol,250,1200,26,Selva caducifolia,5.9,1.3,61.7,0.0,0.1,9.7,0.0,1.8,2.1
8,D1403-120,11/10/1986,"LVro(cep,ct,hu,lon)/3P",Luvisol,250,1200,26,Selva caducifolia,5.9,0.8,53.0,0.5,0.0,9.4,0.1,1.9,2.7
9,D1403-120,11/10/1986,"LVro(cep,ct,hu,lon)/3P",Luvisol,250,1200,26,Selva caducifolia,5.7,0.3,46.5,0.0,0.0,6.6,0.0,2.6,2.4
10,D1403-120,11/10/1986,"LVro(cep,ct,hu,lon)/3P",Luvisol,250,1200,26,Selva caducifolia,5.5,0.2,54.3,0.6,0.2,6.3,0.1,2.8,0.0
12,D1403-124,08/10/1986,RGlep-eu/1P,Regosol,100,800,26,Selva caducifolia,6.2,1.8,77.0,0.0,0.2,6.3,0.0,1.2,4.1

In [18]:
df_limpio = df_limpio.reset_index(drop=True)
df_limpio[df_limpio["PH"] == 0]

Empty DataFrame
Columns: [Identificador del sitio, Fecha, Clave WRB 2014, Grupo suelo, Altitud, Precipitacion media anual, Temperatura media anual, Cobertura de la tierra, PH, Carbon organico, saturacion de bases, Saturacion de sodio, Potasio, Calcio, Sodio, Magnesio, Fosfatos]
Index: []

In [19]:
df_limpio

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,5.8,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4
1,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.0,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.1,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.3,76.6,0.0,0.1,9.4,0.0,1.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,6.8,0.8,49.0,1.4,0.7,9.3,0.4,4.1,0.5
71,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.2,0.9,22.6,1.1,0.2,3.5,0.3,2.1,0.1
72,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.0,0.5,18.7,1.1,0.1,2.9,0.4,2.5,0.0
73,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.1,0.3,24.7,1.6,0.1,2.6,0.4,2.8,0.0
74,D1403-304,12/09/2013,"ALro(cee,ct)/3",Alisol,322,2000,24,Selva subcaducifolia,7.6,0.5,23.5,1.0,0.1,2.5,0.3,3.4,0.0

In [20]:
df_final = df_limpio.copy()

In [21]:
df_final.head()

,Identificador del sitio,Fecha,Clave WRB 2014,Grupo suelo,Altitud,Precipitacion media anual,Temperatura media anual,Cobertura de la tierra,PH,Carbon organico,saturacion de bases,Saturacion de sodio,Potasio,Calcio,Sodio,Magnesio,Fosfatos
0,D1403-106,14/10/1989,RGlep-sk-je(ar)/1P,Regosol,100,1000,26,Selva caducifolia,5.8,0.3,100.0,0.0,0.4,5.6,0.0,1.5,6.4
1,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.0,4.1,79.4,0.4,0.4,14.7,0.1,2.9,5.0
2,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.1,1.3,79.4,0.0,0.1,11.6,0.0,2.2,2.1
3,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.7,70.0,0.0,0.1,8.4,0.0,2.0,2.5
4,D1403-108,09/10/1986,PHcm(lo)/2P,Phaeozem,700,2500,24,Selva subcaducifolia,6.5,0.3,76.6,0.0,0.1,9.4,0.0,1.6,0.0

In [22]:
df_final.shape

(75, 17)

In [23]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Identificador del sitio    75 non-null     object
 1   Fecha                      75 non-null     object
 2   Clave WRB 2014             75 non-null     object
 3   Grupo suelo                75 non-null     object
 4   Altitud                    75 non-null     int64
 5   Precipitacion media anual  75 non-null     int64
 6   Temperatura media anual    75 non-null     int64
 7   Cobertura de la tierra     75 non-null     object
 8   PH                         75 non-null     float64
 9   Carbon organico            75 non-null     float64
 10  saturacion de bases        75 non-null     float64
 11  Saturacion de sodio        75 non-null     float64
 12  Potasio                    75 non-null     float64
 13  Calcio                     75 non-null     float64
 14  Sodio                      75 non-null     float64
 15  Magnesio                   75 non-null     float64
 16  Fosfatos                   75 non-null     float64
dtypes: float64(9), int64(3), object(5)
memory usage: 10.1+ KB

In [24]:
df_final.to_csv("base_suelos_final.csv", index=False)