In [1]:
import pandas as pd

df_fertilizantes = pd.read_csv("Fertilizantes Sniim.csv")
df_fertilizantes.head()

,Fecha,Producto,Concentración (N-P-K),Presentación,Fuente,Municipio,Precio Minimo,Precio Maximo,Precio Frecuente,Obs
0,13/06/2025,Cloruro de potasio,00-00-60,Tonelada,Distribuidora,Oaxaca de Juárez,"13,750","13,770","13,750",Presentación en bulto de 50 kilos (granulado)
1,13/06/2025,Complejo npk triple 17,17-17-17,Tonelada,Distribuidora,Oaxaca de Juárez,"13,170","13,195","13,180",Presentación en bulto de 50 kilos (granulado)
2,13/06/2025,Fosfato diamónico,18-46-00,Tonelada,Distribuidora,Oaxaca de Juárez,"16,350","16,377","16,350",Presentación en bulto de 50 kilos (granulado)
3,13/06/2025,Nitrato de amonio,33.5-00-00,Tonelada,Distribuidora,Oaxaca de Juárez,"11,360","11,390","11,375",Presentación en bulto de 50 kilos (granulado)
4,13/06/2025,Sulfato de amonio,20.5-00-00,Tonelada,Distribuidora,Oaxaca de Juárez,"7,110","7,115","7,115",Presentación en bulto de 50 kilos (polvo granu...

In [2]:
df_fertilizantes.shape

(60, 10)

In [3]:
df_fertilizantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Fecha                  60 non-null     object
 1   Producto               60 non-null     object
 2   Concentración (N-P-K)  60 non-null     object
 3   Presentación           60 non-null     object
 4   Fuente                 60 non-null     object
 5   Municipio              60 non-null     object
 6   Precio Minimo          60 non-null     object
 7   Precio Maximo          60 non-null     object
 8   Precio Frecuente       60 non-null     object
 9   Obs                    60 non-null     object
dtypes: object(10)
memory usage: 4.8+ KB

In [4]:
df_fertilizantes["Fecha"] = pd.to_datetime(
    df_fertilizantes["Fecha"],
    dayfirst=True,
    errors="coerce"
)

In [5]:
df_fertilizantes.dtypes

Fecha                    datetime64[ns]
Producto                         object
Concentración (N-P-K)            object
Presentación                     object
Fuente                           object
Municipio                        object
Precio Minimo                    object
Precio Maximo                    object
Precio Frecuente                 object
Obs                              object
dtype: object

In [6]:
columnas_precio = ["Precio Minimo", "Precio Maximo", "Precio Frecuente"]
for col in columnas_precio:
    df_fertilizantes[col] = (
        df_fertilizantes[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    df_fertilizantes[col] = pd.to_numeric(
        df_fertilizantes[col],
        errors="coerce"
    )
df_fertilizantes.dtypes

Fecha                    datetime64[ns]
Producto                         object
Concentración (N-P-K)            object
Presentación                     object
Fuente                           object
Municipio                        object
Precio Minimo                     int64
Precio Maximo                     int64
Precio Frecuente                  int64
Obs                              object
dtype: object

In [7]:
df_fertilizantes.isnull().sum()

Fecha                    0
Producto                 0
Concentración (N-P-K)    0
Presentación             0
Fuente                   0
Municipio                0
Precio Minimo            0
Precio Maximo            0
Precio Frecuente         0
Obs                      0
dtype: int64

In [8]:
df_fertilizantes.head()

,Fecha,Producto,Concentración (N-P-K),Presentación,Fuente,Municipio,Precio Minimo,Precio Maximo,Precio Frecuente,Obs
0,2025-06-13,Cloruro de potasio,00-00-60,Tonelada,Distribuidora,Oaxaca de Juárez,13750,13770,13750,Presentación en bulto de 50 kilos (granulado)
1,2025-06-13,Complejo npk triple 17,17-17-17,Tonelada,Distribuidora,Oaxaca de Juárez,13170,13195,13180,Presentación en bulto de 50 kilos (granulado)
2,2025-06-13,Fosfato diamónico,18-46-00,Tonelada,Distribuidora,Oaxaca de Juárez,16350,16377,16350,Presentación en bulto de 50 kilos (granulado)
3,2025-06-13,Nitrato de amonio,33.5-00-00,Tonelada,Distribuidora,Oaxaca de Juárez,11360,11390,11375,Presentación en bulto de 50 kilos (granulado)
4,2025-06-13,Sulfato de amonio,20.5-00-00,Tonelada,Distribuidora,Oaxaca de Juárez,7110,7115,7115,Presentación en bulto de 50 kilos (polvo granu...

In [9]:
df_fertilizantes["Producto"].unique()

array(['Cloruro de potasio', 'Complejo npk triple 17',
       'Fosfato diamónico', 'Nitrato de amonio', 'Sulfato de amonio',
       'Urea'], dtype=object)

In [10]:
df_fertilizantes["Producto"].value_counts()

Producto
Cloruro de potasio        10
Complejo npk triple 17    10
Fosfato diamónico         10
Nitrato de amonio         10
Sulfato de amonio         10
Urea                      10
Name: count, dtype: int64

In [11]:
df_fertilizantes["Concentración (N-P-K)"].unique()

array(['00-00-60', '17-17-17', '18-46-00', '33.5-00-00', '20.5-00-00',
       '46-00-00'], dtype=object)

In [12]:
df_fertilizantes[["N", "P", "K"]] = df_fertilizantes[
    "Concentración (N-P-K)"
].str.split("-", expand=True)
df_fertilizantes[["N", "P", "K"]] = df_fertilizantes[
    ["N", "P", "K"]
].astype(float)

In [13]:
df_fertilizantes.head()

,Fecha,Producto,Concentración (N-P-K),Presentación,Fuente,Municipio,Precio Minimo,Precio Maximo,Precio Frecuente,Obs,N,P,K
0,2025-06-13,Cloruro de potasio,00-00-60,Tonelada,Distribuidora,Oaxaca de Juárez,13750,13770,13750,Presentación en bulto de 50 kilos (granulado),0.0,0.0,60.0
1,2025-06-13,Complejo npk triple 17,17-17-17,Tonelada,Distribuidora,Oaxaca de Juárez,13170,13195,13180,Presentación en bulto de 50 kilos (granulado),17.0,17.0,17.0
2,2025-06-13,Fosfato diamónico,18-46-00,Tonelada,Distribuidora,Oaxaca de Juárez,16350,16377,16350,Presentación en bulto de 50 kilos (granulado),18.0,46.0,0.0
3,2025-06-13,Nitrato de amonio,33.5-00-00,Tonelada,Distribuidora,Oaxaca de Juárez,11360,11390,11375,Presentación en bulto de 50 kilos (granulado),33.5,0.0,0.0
4,2025-06-13,Sulfato de amonio,20.5-00-00,Tonelada,Distribuidora,Oaxaca de Juárez,7110,7115,7115,Presentación en bulto de 50 kilos (polvo granu...,20.5,0.0,0.0

In [14]:
cols = list(df_fertilizantes.columns)

cols.remove("N")
cols.remove("P")
cols.remove("K")

posicion = cols.index("Concentración (N-P-K)") + 1

cols = (
    cols[:posicion] +
    ["N", "P", "K"] +
    cols[posicion:]
)

df_fertilizantes = df_fertilizantes[cols]

In [15]:
df_fertilizantes

,Fecha,Producto,Concentración (N-P-K),N,P,K,Presentación,Fuente,Municipio,Precio Minimo,Precio Maximo,Precio Frecuente,Obs
0,2025-06-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13750,13770,13750,Presentación en bulto de 50 kilos (granulado)
1,2025-06-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13170,13195,13180,Presentación en bulto de 50 kilos (granulado)
2,2025-06-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16350,16377,16350,Presentación en bulto de 50 kilos (granulado)
3,2025-06-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11360,11390,11375,Presentación en bulto de 50 kilos (granulado)
4,2025-06-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7110,7115,7115,Presentación en bulto de 50 kilos (polvo granu...
5,2025-06-13,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11550,11598,11550,Presentación en bulto de 50 kilos (granulado)
6,2025-07-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13757,13768,13757,Presentación en bulto de 50 kilos (granulado)
7,2025-07-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13178,13195,13180,Presentación en bulto de 50 kilos (granulado)
8,2025-07-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16355,16362,16362,Presentación en bulto de 50 kilos (granulado)
9,2025-07-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11370,11395,11387,Presentación en bulto de 50 kilos (granulado)
10,2025-07-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7118,7120,7118,Presentación en bulto de 50 kilos (polvo granu...
11,2025-07-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11558,11580,11558,Presentación en bulto de 50 kilos (granulado)
12,2025-08-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13760,13785,13760,Presentación en bulto de 50 kilos (granulado)
13,2025-08-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13185,13205,13185,Presentación en bulto de 50 kilos (granulado)
14,2025-08-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16360,16370,16370,Presentación en bulto de 50 kilos (granulado)
15,2025-08-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11375,11397,11375,Presentación en bulto de 50 kilos (granulado)
16,2025-08-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7120,7122,7122,Presentación en bulto de 50 kilos (polvo granu...
17,2025-08-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11562,11588,11565,Presentación en bulto de 50 kilos (granulado)
18,2025-09-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13755,13775,13755,Presentación en bulto de 50 kilos (granulado)
19,2025-09-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13182,13195,13190,Presentación en bulto de 50 kilos (granulado)
20,2025-09-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16365,16375,16365,Presentación en bulto de 50 kilos (granulado)
21,2025-09-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11370,11390,11380,Presentación en bulto de 50 kilos (granulado)
22,2025-09-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7120,7122,7120,Presentación en bulto de 50 kilos (polvo granu...
23,2025-09-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11560,11582,11565,Presentación en bulto de 50 kilos (granulado)
24,2025-10-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13768,13785,13768,Presentación en bulto de 50 kilos (granulado)
25,2025-10-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13190,13210,13195,Presentación en bulto de 50 kilos (granulado)
26,2025-10-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16375,16390,16385,Presentación en bulto de 50 kilos (granulado)
27,2025-10-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11370,11390,11380,Presentación en bulto de 50 kilos (granulado)
28,2025-10-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7122,7125,7125,Presentación en bulto de 50 kilos (polvo granu...
29,2025-10-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11570,11585,11575,Presentación en bulto de 50 kilos (granulado)
30,2025-11-14,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13775,13790,13780,Presentación en bulto de 50 kilos (granulado)
31,2025-11-14,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13198,13220,13198,Presentación en bulto de 50 kilos (granulado)
32,2025-11-14,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16375,16385,16380,Presentación en bulto de 50 kilos (granulado)
33,2025-11-14,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11375,11395,11375,Presentación en bulto de 50 kilos (granulado)
34,2025-11-14,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7122,7125,7122,Presentación en bulto de 50 kilos (polvo granu...
35,2025-11-14,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11570,11595,11580,Presentación en bulto de 50 kilos (granulado)
36,2025-12-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13780,13798,13790,Presentación en bulto de 50 kilos (granulado)
37,2025-12-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13200,13230,13200,Presentación en bulto de 50 kilos (granulado)
38,2025-12-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16378,16395,16380,Presentación en bulto de 50 kilos (granulado)
39,2025-12-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11385,11395,11390,Presentación en bulto de 50 kilos (granulado)
40,2025-12-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7128,7130,7128,Presentación en bulto de 50 kilos (polvo granu...
41,2025-12-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11580,11598,11585,Presentación en bulto de 50 kilos (granulado)
42,2026-01-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13785,13800,13785,Presentación en bulto de 50 kilos (granulado)
43,2026-01-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13220,13245,13220,Presentación en bulto de 50 kilos (granulado)
44,2026-01-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16390,16430,16390,Presentación en bulto de 50 kilos (granulado)
45,2026-01-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11390,11410,11400,Presentación en bulto de 50 kilos (granulado)
46,2026-01-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7130,7135,7130,Presentación en bulto de 50 kilos (polvo granu...
47,2026-01-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11590,11610,11600,Presentación en bulto de 50 kilos (granulado)
48,2026-02-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13810,13848,13810,Presentación en bulto de 50 kilos (granulado)
49,2026-02-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13232,13255,13232,Presentación en bulto de 50 kilos (granulado)
50,2026-02-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16410,16438,16410,Presentación en bulto de 50 kilos (granulado)
51,2026-02-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11420,11445,11420,Presentación en bulto de 50 kilos (granulado)
52,2026-02-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7138,7140,7138,Presentación en bulto de 50 kilos (polvo granu...
53,2026-02-13,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11615,11628,11615,Presentación en bulto de 50 kilos (granulado)
54,2026-03-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13200,13220,13220,Presentación en bulto de 50 kilos (granulado)
55,2026-03-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13410,13440,13410,Presentación en bulto de 50 kilos (granulado)
56,2026-03-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16600,16640,16640,Presentación en bulto de 50 kilos (granulado)
57,2026-03-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11630,11690,11690,Presentación en bulto de 50 kilos (granulado)
58,2026-03-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,8570,8600,8570,Presentación en bulto de 50 kilos (polvo granu...
59,2026-03-13,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11440,11490,11490,Presentación en bulto de 50 kilos (granulado)

In [16]:
df_fertilizantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Fecha                  60 non-null     datetime64[ns]
 1   Producto               60 non-null     object
 2   Concentración (N-P-K)  60 non-null     object
 3   N                      60 non-null     float64
 4   P                      60 non-null     float64
 5   K                      60 non-null     float64
 6   Presentación           60 non-null     object
 7   Fuente                 60 non-null     object
 8   Municipio              60 non-null     object
 9   Precio Minimo          60 non-null     int64
 10  Precio Maximo          60 non-null     int64
 11  Precio Frecuente       60 non-null     int64
 12  Obs                    60 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(3), object(6)
memory usage: 6.2+ KB

In [17]:
df_fertilizantes["Presentacion kg"] = 1000
df_fertilizantes

,Fecha,Producto,Concentración (N-P-K),N,P,K,Presentación,Fuente,Municipio,Precio Minimo,Precio Maximo,Precio Frecuente,Obs,Presentacion kg
0,2025-06-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13750,13770,13750,Presentación en bulto de 50 kilos (granulado),1000
1,2025-06-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13170,13195,13180,Presentación en bulto de 50 kilos (granulado),1000
2,2025-06-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16350,16377,16350,Presentación en bulto de 50 kilos (granulado),1000
3,2025-06-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11360,11390,11375,Presentación en bulto de 50 kilos (granulado),1000
4,2025-06-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7110,7115,7115,Presentación en bulto de 50 kilos (polvo granu...,1000
5,2025-06-13,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11550,11598,11550,Presentación en bulto de 50 kilos (granulado),1000
6,2025-07-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13757,13768,13757,Presentación en bulto de 50 kilos (granulado),1000
7,2025-07-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13178,13195,13180,Presentación en bulto de 50 kilos (granulado),1000
8,2025-07-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16355,16362,16362,Presentación en bulto de 50 kilos (granulado),1000
9,2025-07-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11370,11395,11387,Presentación en bulto de 50 kilos (granulado),1000
10,2025-07-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7118,7120,7118,Presentación en bulto de 50 kilos (polvo granu...,1000
11,2025-07-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11558,11580,11558,Presentación en bulto de 50 kilos (granulado),1000
12,2025-08-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13760,13785,13760,Presentación en bulto de 50 kilos (granulado),1000
13,2025-08-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13185,13205,13185,Presentación en bulto de 50 kilos (granulado),1000
14,2025-08-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16360,16370,16370,Presentación en bulto de 50 kilos (granulado),1000
15,2025-08-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11375,11397,11375,Presentación en bulto de 50 kilos (granulado),1000
16,2025-08-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7120,7122,7122,Presentación en bulto de 50 kilos (polvo granu...,1000
17,2025-08-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11562,11588,11565,Presentación en bulto de 50 kilos (granulado),1000
18,2025-09-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13755,13775,13755,Presentación en bulto de 50 kilos (granulado),1000
19,2025-09-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13182,13195,13190,Presentación en bulto de 50 kilos (granulado),1000
20,2025-09-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16365,16375,16365,Presentación en bulto de 50 kilos (granulado),1000
21,2025-09-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11370,11390,11380,Presentación en bulto de 50 kilos (granulado),1000
22,2025-09-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7120,7122,7120,Presentación en bulto de 50 kilos (polvo granu...,1000
23,2025-09-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11560,11582,11565,Presentación en bulto de 50 kilos (granulado),1000
24,2025-10-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13768,13785,13768,Presentación en bulto de 50 kilos (granulado),1000
25,2025-10-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13190,13210,13195,Presentación en bulto de 50 kilos (granulado),1000
26,2025-10-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16375,16390,16385,Presentación en bulto de 50 kilos (granulado),1000
27,2025-10-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11370,11390,11380,Presentación en bulto de 50 kilos (granulado),1000
28,2025-10-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7122,7125,7125,Presentación en bulto de 50 kilos (polvo granu...,1000
29,2025-10-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11570,11585,11575,Presentación en bulto de 50 kilos (granulado),1000
30,2025-11-14,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13775,13790,13780,Presentación en bulto de 50 kilos (granulado),1000
31,2025-11-14,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13198,13220,13198,Presentación en bulto de 50 kilos (granulado),1000
32,2025-11-14,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16375,16385,16380,Presentación en bulto de 50 kilos (granulado),1000
33,2025-11-14,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11375,11395,11375,Presentación en bulto de 50 kilos (granulado),1000
34,2025-11-14,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7122,7125,7122,Presentación en bulto de 50 kilos (polvo granu...,1000
35,2025-11-14,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11570,11595,11580,Presentación en bulto de 50 kilos (granulado),1000
36,2025-12-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13780,13798,13790,Presentación en bulto de 50 kilos (granulado),1000
37,2025-12-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13200,13230,13200,Presentación en bulto de 50 kilos (granulado),1000
38,2025-12-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16378,16395,16380,Presentación en bulto de 50 kilos (granulado),1000
39,2025-12-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11385,11395,11390,Presentación en bulto de 50 kilos (granulado),1000
40,2025-12-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7128,7130,7128,Presentación en bulto de 50 kilos (polvo granu...,1000
41,2025-12-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11580,11598,11585,Presentación en bulto de 50 kilos (granulado),1000
42,2026-01-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13785,13800,13785,Presentación en bulto de 50 kilos (granulado),1000
43,2026-01-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13220,13245,13220,Presentación en bulto de 50 kilos (granulado),1000
44,2026-01-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16390,16430,16390,Presentación en bulto de 50 kilos (granulado),1000
45,2026-01-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11390,11410,11400,Presentación en bulto de 50 kilos (granulado),1000
46,2026-01-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7130,7135,7130,Presentación en bulto de 50 kilos (polvo granu...,1000
47,2026-01-15,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11590,11610,11600,Presentación en bulto de 50 kilos (granulado),1000
48,2026-02-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13810,13848,13810,Presentación en bulto de 50 kilos (granulado),1000
49,2026-02-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13232,13255,13232,Presentación en bulto de 50 kilos (granulado),1000
50,2026-02-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16410,16438,16410,Presentación en bulto de 50 kilos (granulado),1000
51,2026-02-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11420,11445,11420,Presentación en bulto de 50 kilos (granulado),1000
52,2026-02-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,7138,7140,7138,Presentación en bulto de 50 kilos (polvo granu...,1000
53,2026-02-13,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11615,11628,11615,Presentación en bulto de 50 kilos (granulado),1000
54,2026-03-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Tonelada,Distribuidora,Oaxaca de Juárez,13200,13220,13220,Presentación en bulto de 50 kilos (granulado),1000
55,2026-03-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Tonelada,Distribuidora,Oaxaca de Juárez,13410,13440,13410,Presentación en bulto de 50 kilos (granulado),1000
56,2026-03-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,16600,16640,16640,Presentación en bulto de 50 kilos (granulado),1000
57,2026-03-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11630,11690,11690,Presentación en bulto de 50 kilos (granulado),1000
58,2026-03-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,8570,8600,8570,Presentación en bulto de 50 kilos (polvo granu...,1000
59,2026-03-13,Urea,46-00-00,46.0,0.0,0.0,Tonelada,Distribuidora,Oaxaca de Juárez,11440,11490,11490,Presentación en bulto de 50 kilos (granulado),1000

In [18]:
df_fertilizantes = df_fertilizantes.drop(columns=["Presentación"])

In [19]:
df_fertilizantes

,Fecha,Producto,Concentración (N-P-K),N,P,K,Fuente,Municipio,Precio Minimo,Precio Maximo,Precio Frecuente,Obs,Presentacion kg
0,2025-06-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13750,13770,13750,Presentación en bulto de 50 kilos (granulado),1000
1,2025-06-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13170,13195,13180,Presentación en bulto de 50 kilos (granulado),1000
2,2025-06-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16350,16377,16350,Presentación en bulto de 50 kilos (granulado),1000
3,2025-06-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11360,11390,11375,Presentación en bulto de 50 kilos (granulado),1000
4,2025-06-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7110,7115,7115,Presentación en bulto de 50 kilos (polvo granu...,1000
5,2025-06-13,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11550,11598,11550,Presentación en bulto de 50 kilos (granulado),1000
6,2025-07-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13757,13768,13757,Presentación en bulto de 50 kilos (granulado),1000
7,2025-07-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13178,13195,13180,Presentación en bulto de 50 kilos (granulado),1000
8,2025-07-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16355,16362,16362,Presentación en bulto de 50 kilos (granulado),1000
9,2025-07-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11370,11395,11387,Presentación en bulto de 50 kilos (granulado),1000
10,2025-07-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7118,7120,7118,Presentación en bulto de 50 kilos (polvo granu...,1000
11,2025-07-15,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11558,11580,11558,Presentación en bulto de 50 kilos (granulado),1000
12,2025-08-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13760,13785,13760,Presentación en bulto de 50 kilos (granulado),1000
13,2025-08-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13185,13205,13185,Presentación en bulto de 50 kilos (granulado),1000
14,2025-08-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16360,16370,16370,Presentación en bulto de 50 kilos (granulado),1000
15,2025-08-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11375,11397,11375,Presentación en bulto de 50 kilos (granulado),1000
16,2025-08-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7120,7122,7122,Presentación en bulto de 50 kilos (polvo granu...,1000
17,2025-08-15,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11562,11588,11565,Presentación en bulto de 50 kilos (granulado),1000
18,2025-09-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13755,13775,13755,Presentación en bulto de 50 kilos (granulado),1000
19,2025-09-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13182,13195,13190,Presentación en bulto de 50 kilos (granulado),1000
20,2025-09-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16365,16375,16365,Presentación en bulto de 50 kilos (granulado),1000
21,2025-09-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11370,11390,11380,Presentación en bulto de 50 kilos (granulado),1000
22,2025-09-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7120,7122,7120,Presentación en bulto de 50 kilos (polvo granu...,1000
23,2025-09-15,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11560,11582,11565,Presentación en bulto de 50 kilos (granulado),1000
24,2025-10-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13768,13785,13768,Presentación en bulto de 50 kilos (granulado),1000
25,2025-10-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13190,13210,13195,Presentación en bulto de 50 kilos (granulado),1000
26,2025-10-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16375,16390,16385,Presentación en bulto de 50 kilos (granulado),1000
27,2025-10-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11370,11390,11380,Presentación en bulto de 50 kilos (granulado),1000
28,2025-10-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7122,7125,7125,Presentación en bulto de 50 kilos (polvo granu...,1000
29,2025-10-15,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11570,11585,11575,Presentación en bulto de 50 kilos (granulado),1000
30,2025-11-14,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13775,13790,13780,Presentación en bulto de 50 kilos (granulado),1000
31,2025-11-14,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13198,13220,13198,Presentación en bulto de 50 kilos (granulado),1000
32,2025-11-14,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16375,16385,16380,Presentación en bulto de 50 kilos (granulado),1000
33,2025-11-14,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11375,11395,11375,Presentación en bulto de 50 kilos (granulado),1000
34,2025-11-14,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7122,7125,7122,Presentación en bulto de 50 kilos (polvo granu...,1000
35,2025-11-14,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11570,11595,11580,Presentación en bulto de 50 kilos (granulado),1000
36,2025-12-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13780,13798,13790,Presentación en bulto de 50 kilos (granulado),1000
37,2025-12-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13200,13230,13200,Presentación en bulto de 50 kilos (granulado),1000
38,2025-12-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16378,16395,16380,Presentación en bulto de 50 kilos (granulado),1000
39,2025-12-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11385,11395,11390,Presentación en bulto de 50 kilos (granulado),1000
40,2025-12-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7128,7130,7128,Presentación en bulto de 50 kilos (polvo granu...,1000
41,2025-12-15,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11580,11598,11585,Presentación en bulto de 50 kilos (granulado),1000
42,2026-01-15,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13785,13800,13785,Presentación en bulto de 50 kilos (granulado),1000
43,2026-01-15,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13220,13245,13220,Presentación en bulto de 50 kilos (granulado),1000
44,2026-01-15,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16390,16430,16390,Presentación en bulto de 50 kilos (granulado),1000
45,2026-01-15,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11390,11410,11400,Presentación en bulto de 50 kilos (granulado),1000
46,2026-01-15,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7130,7135,7130,Presentación en bulto de 50 kilos (polvo granu...,1000
47,2026-01-15,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11590,11610,11600,Presentación en bulto de 50 kilos (granulado),1000
48,2026-02-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13810,13848,13810,Presentación en bulto de 50 kilos (granulado),1000
49,2026-02-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13232,13255,13232,Presentación en bulto de 50 kilos (granulado),1000
50,2026-02-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16410,16438,16410,Presentación en bulto de 50 kilos (granulado),1000
51,2026-02-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11420,11445,11420,Presentación en bulto de 50 kilos (granulado),1000
52,2026-02-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,7138,7140,7138,Presentación en bulto de 50 kilos (polvo granu...,1000
53,2026-02-13,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11615,11628,11615,Presentación en bulto de 50 kilos (granulado),1000
54,2026-03-13,Cloruro de potasio,00-00-60,0.0,0.0,60.0,Distribuidora,Oaxaca de Juárez,13200,13220,13220,Presentación en bulto de 50 kilos (granulado),1000
55,2026-03-13,Complejo npk triple 17,17-17-17,17.0,17.0,17.0,Distribuidora,Oaxaca de Juárez,13410,13440,13410,Presentación en bulto de 50 kilos (granulado),1000
56,2026-03-13,Fosfato diamónico,18-46-00,18.0,46.0,0.0,Distribuidora,Oaxaca de Juárez,16600,16640,16640,Presentación en bulto de 50 kilos (granulado),1000
57,2026-03-13,Nitrato de amonio,33.5-00-00,33.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,11630,11690,11690,Presentación en bulto de 50 kilos (granulado),1000
58,2026-03-13,Sulfato de amonio,20.5-00-00,20.5,0.0,0.0,Distribuidora,Oaxaca de Juárez,8570,8600,8570,Presentación en bulto de 50 kilos (polvo granu...,1000
59,2026-03-13,Urea,46-00-00,46.0,0.0,0.0,Distribuidora,Oaxaca de Juárez,11440,11490,11490,Presentación en bulto de 50 kilos (granulado),1000

In [20]:
df_fertilizantes.to_csv(
    "fertilizantes_oaxaca_final.csv",
    index=False,
    encoding="utf-8-sig"
)